rulesets:
  - name: require-pr
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include: ["~DEFAULT_BRANCH"]
      repository_name:
        include: ["~ALL"]
    rules:
      non_fast_forward: true
      pull_request:
        required_approving_review_count: 0
        dismiss_stale_reviews_on_push: false

  - name: require-pr-validation
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include: ["~DEFAULT_BRANCH"]
      repository_name:
        include: ["~ALL"]
    rules:
      non_fast_forward: true
      required_status_checks:
        strict: false
        checks:
          - context: "PR Validation"
