project-number: 6

projects:
  - name: cheburnet
    knowledge-base: nsalab-tmn/cheburnet-knowledge-base
    conventions-path: conventions
    repos:
      - nsalab-tmn/cheburnet-knowledge-base
      - nsalab-tmn/cheburnet-vpn
      - nsalab-tmn/cheburnet-infra
      - nsalab-tmn/cheburnet-mtproxy
      - nsalab-tmn/cheburnet-monitoring
      - nsalab-tmn/cheburnet-router
      - nsalab-tmn/cheburnet-gitops
