name: pinned-sync
run-name: "[${{github.run_number}}] Pinned sync [${{github.event_name}}]"

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]
  schedule:
    - cron: '0 9 * * 1'  # Monday 9am UTC fallback
  workflow_dispatch:

jobs:
  pinned-sync:
    uses: nsalab-tmn/github-automation/.github/workflows/reusable-pinned-sync.yaml@main
