name: stale-check
run-name: "[${{github.run_number}}] Stale check [${{github.event_name}}]"

on:
  schedule:
    - cron: '0 9 * * 1'  # Monday 9am UTC
  workflow_dispatch:

jobs:
  stale-check:
    uses: nsalab-tmn/github-automation/.github/workflows/reusable-stale-check.yaml@main
    with:
      days-before-stale: 30
      exempt-labels: pinned,in-progress
