name: stale-pr
run-name: "[${{github.run_number}}] Stale PR check [${{github.event_name}}]"

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  stale-pr:
    uses: nsalab-tmn/github-automation/.github/workflows/reusable-stale-pr.yaml@main
    with:
      days-before-stale: 14
      days-before-close: 7
      exempt-labels: pinned,in-progress
