name: terraform-plan
run-name: "[${{github.run_number}}] Terraform plan [${{github.event_name}}]"

on:
  pull_request:
    paths:
      - "terraform/**"
  workflow_dispatch:

jobs:
  plan:
    uses: nsalab-tmn/github-automation/.github/workflows/reusable-terraform-plan.yaml@main
    with:
      working-directory: terraform
    secrets:
      doorman-client-id: ${{ secrets.DOORMAN_CLIENT_ID }}
      doorman-private-key: ${{ secrets.DOORMAN_PRIVATE_KEY }}
      arm-client-id: ${{ secrets.ARM_CLIENT_ID }}
      arm-client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
      arm-tenant-id: ${{ secrets.ARM_TENANT_ID }}
      arm-subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
